version: '3'
services:
  netcore-counter:
    build: .
    depends_on:
      - "redis"
    ports:
      - "${COUNTER_WEBPORT}:5000"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  redis:
    image: "redis:5.0.6-alpine"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
