version: '3'
services:
  netcore-counter:
    build: .
    depends_on:
      - "redis"
    ports:
      - "5010:5000"
  redis:
    image: "redis:5.0.6-alpine"
    command: redis-server --requirepass password
