version: '3'
services:
  next-netcore-counter:
    build: .
    depends_on:
      - "netcore-counter-redis"
    ports:
      - "${NEXT_COUNTER_HTTP_EXT_PORT}:${COUNTER_HTTP_INT_PORT}"
    environment:
      - COUNTER_HTTP_INT_PORT=${COUNTER_HTTP_INT_PORT}
      - COUNTER_VERSION=${COUNTER_VERSION}
      - FEATUREMANAGEMENT__PERSISTENCIANEXTCOUNTER=${NEXT_COUNTER_FEATURE_NEXT_COUNTER}
      - NEXTCOUNTER__PROTOCOLO=${NEXTCOUNTER_PROTOCOLO}
      - NEXTCOUNTER__HOST=${NEXTCOUNTER_HOST_REDIS}
      - NEXTCOUNTER__PORT=${COUNTER_HTTP_INT_PORT}
      - REDIS__HOST=${REDIS_HOST}
      - REDIS__PORT=${REDIS_PORT}
      - REDIS__PASSWORD=${REDIS_PASSWORD}
      - REDIS__INSTANCE=${REDIS_INSTANCE}
  netcore-counter-redis:
    build: .
    depends_on:
      - "redis"
    ports:
      - "${COUNTER_REDIS_HTTP_EXT_PORT}:${COUNTER_HTTP_INT_PORT}"
    environment:
      - COUNTER_HTTP_INT_PORT=${COUNTER_HTTP_INT_PORT}
      - COUNTER_VERSION=${COUNTER_VERSION}
      - FEATUREMANAGEMENT__PERSISTENCIANEXTCOUNTER=${COUNTER_REDIS_FEATURE_NEXT_COUNTER}
      - NEXTCOUNTER__PROTOCOLO=${NEXTCOUNTER_PROTOCOLO}
      - NEXTCOUNTER__HOST=${NEXTCOUNTER_HOST_NEXT}
      - NEXTCOUNTER__PORT=${COUNTER_HTTP_INT_PORT}
      - REDIS__HOST=${REDIS_HOST}
      - REDIS__PORT=${REDIS_PORT}
      - REDIS__PASSWORD=${REDIS_PASSWORD}
      - REDIS__INSTANCE=${REDIS_INSTANCE}
  redis:
    image: "redis:${REDIS_IMAGE_TAG}"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
