apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ template "netcore-counter.fullname" . }}
  name: {{ template "netcore-counter.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: {{ template "netcore-counter.fullname" . }}
  template:
    metadata:
      labels:
        run: {{ template "netcore-counter.fullname" . }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - {{ template "netcore-counter.fullname" . }}
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        name: {{ template "netcore-counter.fullname" . }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        env:
          - name: COUNTER_VERSION
            value: {{ .Values.tag }}
          - name: REDIS__HOST
            value: {{ .Release.Name }}-redis-master
          - name: REDIS__PORT
            value: "6379"
          - name: REDIS__INSTANCE
            value: {{ template "netcore-counter.fullname" . }}
          - name: REDIS__PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-redis
                key: redis-password
        resources:
{{ toYaml .Values.resources | indent 10 }}
