apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: netcore-counter
  name: netcore-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: netcore-counter
  template:
    metadata:
      labels:
        run: netcore-counter
    spec:
      containers:
      - image: ureure/netcore-counter:0.1-unstable
        name: netcore-counter
        livenessProbe:
          httpGet:
            path: /api/v1/Health/live
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/Health/ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
          - name: COUNTER_VERSION
            value: 0.1-unstable
          - name: REDIS__HOST
            value: redis
          - name: REDIS__PORT
            value: "6379"
          - name: REDIS__INSTANCE
            value: netcore-counter
          - name: REDIS__PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: run
                  operator: In
                  values:
                  - netcore-counter
              topologyKey: "kubernetes.io/hostname"
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: "kubernetes.io/hostname"
