apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: netcore-counter-next
  name: netcore-counter-next
spec:
  replicas: 1
  selector:
    matchLabels:
      run: netcore-counter-next
  template:
    metadata:
      labels:
        run: netcore-counter-next
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - netcore-counter-next
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: ureure/netcore-counter:0.7-unstable
        name: netcore-counter-next
        livenessProbe:
          httpGet:
            path: /api/v1/Health/live
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
          - name: COUNTER_VERSION
            value: "0.7-unstable - MICROSERVICIO 2"
          - name: FEATUREMANAGEMENT__PERSISTENCIANEXTCOUNTER
            value: "true"
          - name: NEXTCOUNTER__PROTOCOLO
            value: "http"
          - name: NEXTCOUNTER__HOST
            value: netcore-counter-redis
          - name: NEXTCOUNTER__PORT
            value: "5000"
          - name: REDIS__HOST
            value: redis
          - name: REDIS__PORT
            value: "6379"
          - name: REDIS__INSTANCE
            value: netcore-counter-redis
          - name: REDIS__PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
