apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netcore-counter-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      run: netcore-counter
  endpoints:
  - port: web
    interval: 10s
