apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netcore-counter-servicemonitor-redis
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      run: netcore-counter-redis
  endpoints:
  - port: web
    interval: 10s
